Expanded chosable time frame
tybug/snitchvisbot pull request #4
Opened 2022-09-14 21:43 UTC by Creepi0n

Added hour, minute and second as optional parameters for --start and --end

2022-09-14 22:00 UTC, tybug requested changes

2022-09-14 22:00 UTC, Liam-DeVoe commented on command.py
> +                    "`mm/dd/yyyy` or `mm/dd/yyyy/hh/mm/ss`.")
`mm/dd/yyyy/hh/mm/ss` is definitely not a good format for this. Should be eg `7/12/2022 8:02:20 PM` as in the comment above. Ideally would also support 24 hour clocks when AM/PM isn't specified.

I'm guessing you had trouble getting `human_datetime` to be passed both arguments when they're separated with a space - you can achieve this by setting `convert_mode="together"` in the `Arg` definition of start and end. See --bounds for an example: https://github.com/tybug/snitchvisbot/blob/5566d5438daad13ed0e989c4c62aac204e76d38a/main.py#L679

2022-09-14 22:00 UTC, tybug commented on command.py
> +        if parsing_i != 2:
combine these two conditions

2022-09-14 22:00 UTC, tybug commented on command.py
> +        hour=0
spaces between equals please

`hour = 0`

2022-09-15 00:37 UTC, Gjum commented
Why write such a complex parser for a simple date? Use [datetime.strptime](https://docs.python.org/3/library/datetime.html#datetime.datetime.strptime) for a builtin parser, or [pandas.to_datetime](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html) if you want to allow many flexible formats.

2022-09-15 01:11 UTC, tybug commented
Mostly for nice error messages. strptime errors can be pretty inscrutable if you don't know format specifiers (`%Y/%m/%d` might be understandable to most, but `%Y/%m/%d %H:%M:%S %p` significantly less so with the %p).

I could just return a generic error I guess, eg `Invalid value; must match eg 2022/07/03 06:03:20 PM, AM/PM is optional if using 24 hour clock`, but I dunno I think that's more confusing than pointing out the exact error location.

2023-07-15 01:47 UTC, tybug commented
I've decided that @Gjum was right and maintaining our own timestamp parser is (probably) more trouble than it's worth. It's nice having granular control over formats and error messages, but supporting all reasonable formats is a huge pain. 

I've offloaded this to the `dateparser` library for now, with the added bonus that things like `three weeks ago` are now valid inputs everywhere a datetime is accepted.

2023-07-15 01:49 UTC, merged